-- Script para insertar profesionales SIN especialidad pero CON email temporal
-- Los emails son temporales y se pueden modificar después
-- Ejecutar en Supabase SQL Editor

INSERT INTO profiles (id, full_name, email, role, is_active) VALUES
  (gen_random_uuid(), 'Abril Villalba', 'abril.villalba@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Agostina Acevedo', 'agostina.acevedo@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Alejo Herrera', 'alejo.herrera@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Alvaro Robledo', 'alvaro.robledo@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Amber Alleguero', 'amber.alleguero@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Antonella Vera Romero', 'antonella.vera@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Beltran Coronel', 'beltran.coronel@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Benjamín Wasinger', 'benjamin.wasinger@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Benjamin Benitez', 'benjamin.benitez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Benjamin Mamani', 'benjamin.mamani@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Bruno Orellana', 'bruno.orellana@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Camilo Maciel', 'camilo.maciel@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Candela Torres', 'candela.torres@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Carla Fernandez', 'carla.fernandez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Cata Gomez', 'cata.gomez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Constantino', 'constantino@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Dylan Godoy', 'dylan.godoy@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Elias Alvelo', 'elias.alvelo@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Ema Cisneros', 'ema.cisneros@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Emanuel Cisneros', 'emanuel.cisneros@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Emilio Russo', 'emilio.russo@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Emily Garcia', 'emily.garcia@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Emma Dos Santos', 'emma.dossantos@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Espiniza Joaquin', 'espiniza.joaquin@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Felipe Galvan', 'felipe.galvan@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Felipe Herterich', 'felipe.herterich@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Felipe Portillo', 'felipe.portillo@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Fran Maciel Fagundez', 'fran.maciel@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Franco Aguado', 'franco.aguado@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Gabriel Rodriguez', 'gabriel.rodriguez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Gadiel Huaylla', 'gadiel.huaylla@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Helena Martinez', 'helena.martinez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Hernan Flores', 'hernan.flores@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Ian Orrego', 'ian.orrego@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Ignacio Gonzalo', 'ignacio.gonzalo@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Ignacio Herrera', 'ignacio.herrera@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Ignacio Ojeda', 'ignacio.ojeda@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Iker Flores', 'iker.flores@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Isaias Baez', 'isaias.baez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Italia Chavez', 'italia.chavez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Joaquin Espindola', 'joaquin.espindola@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Joaquin Garelli', 'joaquin.garelli@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Kaila Villalba', 'kaila.villalba@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Liam Mendez', 'liam.mendez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Lian Mendez', 'lian.mendez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Lionel Escobar', 'lionel.escobar@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Luciano Nuñez', 'luciano.nunez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Luis Lopez', 'luis.lopez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Luan Robledo', 'luan.robledo@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Maite Barraza', 'maite.barraza@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Martina Cerchiari', 'martina.cerchiari@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Mateo Anse', 'mateo.anse@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Mateo Molina', 'mateo.molina@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Matias Luna', 'matias.luna@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Maximo Canseco', 'maximo.canseco@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Nahitan Oña', 'nahitan.ona@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Naomi', 'naomi@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Noah Fagundez', 'noah.fagundez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Otto Stale', 'otto.stale@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Pedro Lencina', 'pedro.lencina@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Pia Saavedra', 'pia.saavedra@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Pilar Mamani', 'pilar.mamani@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Samuel Godoy', 'samuel.godoy@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Santiago Wasinger', 'santiago.wasinger@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Santino Lopez', 'santino.lopez@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Stefano Sosa', 'stefano.sosa@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Taylor Quiroga', 'taylor.quiroga@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Thiago Cider', 'thiago.cider@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Thiago Rusch', 'thiago.rusch@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Tiziano', 'tiziano@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Triana Heis', 'triana.heis@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Valentino Meza', 'valentino.meza@temp.espaciodesafios.cl', 'professional', true),
  (gen_random_uuid(), 'Victoria Herrera', 'victoria.herrera@temp.espaciodesafios.cl', 'professional', true);

-- Verificar la inserción
SELECT COUNT(*) as total_profesionales FROM profiles WHERE role = 'professional';
