-- Script para insertar profesionales en la base de datos
-- Ejecutar en Supabase SQL Editor
-- Nota: Este script inserta solo los perfiles. Los usuarios de autenticación deben crearse por separado

INSERT INTO profiles (id, email, full_name, specialty, role, is_active) VALUES
  (gen_random_uuid(), 'abril.villalba@espaciodesafios.cl', 'Abril Villalba', 'Psicomotricidad Relacional', 'professional', true),
  (gen_random_uuid(), 'agostina.acevedo@espaciodesafios.cl', 'Agostina Acevedo', 'Estimulación Temprana', 'professional', true),
  (gen_random_uuid(), 'alejo.herrera@espaciodesafios.cl', 'Alejo Herrera', 'Psicopedagogía', 'professional', true),
  (gen_random_uuid(), 'alvaro.robledo@espaciodesafios.cl', 'Alvaro Robledo', 'Psicología', 'professional', true),
  (gen_random_uuid(), 'amber.alleguero@espaciodesafios.cl', 'Amber Alleguero', 'Fonoaudiología', 'professional', true),
  (gen_random_uuid(), 'antonella.vera@espaciodesafios.cl', 'Antonella Vera Romero', 'Terapia Ocupacional', 'professional', true),
  (gen_random_uuid(), 'beltran.coronel@espaciodesafios.cl', 'Beltran Coronel', 'Kinesiología', 'professional', true),
  (gen_random_uuid(), 'benjamin.wasinger@espaciodesafios.cl', 'Benjamín Wasinger', 'Musicoterapia', 'professional', true),
  (gen_random_uuid(), 'benjamin.benitez@espaciodesafios.cl', 'Benjamin Benitez', 'Psicomotricidad Relacional', 'professional', true),
  (gen_random_uuid(), 'benjamin.mamani@espaciodesafios.cl', 'Benjamin Mamani', 'Estimulación Temprana', 'professional', true),
  (gen_random_uuid(), 'bruno.orellana@espaciodesafios.cl', 'Bruno Orellana', 'Psicopedagogía', 'professional', true),
  (gen_random_uuid(), 'camilo.maciel@espaciodesafios.cl', 'Camilo Maciel', 'Psicología', 'professional', true),
  (gen_random_uuid(), 'candela.torres@espaciodesafios.cl', 'Candela Torres', 'Fonoaudiología', 'professional', true),
  (gen_random_uuid(), 'carla.fernandez@espaciodesafios.cl', 'Carla Fernandez', 'Terapia Ocupacional', 'professional', true),
  (gen_random_uuid(), 'cata.gomez@espaciodesafios.cl', 'Cata Gomez', 'Kinesiología', 'professional', true),
  (gen_random_uuid(), 'constantino@espaciodesafios.cl', 'Constantino', 'Musicoterapia', 'professional', true),
  (gen_random_uuid(), 'dylan.godoy@espaciodesafios.cl', 'Dylan Godoy', 'Psicomotricidad Relacional', 'professional', true),
  (gen_random_uuid(), 'elias.alvelo@espaciodesafios.cl', 'Elias Alvelo', 'Estimulación Temprana', 'professional', true),
  (gen_random_uuid(), 'ema.cisneros@espaciodesafios.cl', 'Ema Cisneros', 'Psicopedagogía', 'professional', true),
  (gen_random_uuid(), 'emanuel.cisneros@espaciodesafios.cl', 'Emanuel Cisneros', 'Psicología', 'professional', true),
  (gen_random_uuid(), 'emilio.russo@espaciodesafios.cl', 'Emilio Russo', 'Fonoaudiología', 'professional', true),
  (gen_random_uuid(), 'emily.garcia@espaciodesafios.cl', 'Emily Garcia', 'Terapia Ocupacional', 'professional', true),
  (gen_random_uuid(), 'emma.dossantos@espaciodesafios.cl', 'Emma Dos Santos', 'Kinesiología', 'professional', true),
  (gen_random_uuid(), 'joaquin.espiniza@espaciodesafios.cl', 'Espiniza Joaquin', 'Musicoterapia', 'professional', true),
  (gen_random_uuid(), 'felipe.galvan@espaciodesafios.cl', 'Felipe Galvan', 'Psicomotricidad Relacional', 'professional', true),
  (gen_random_uuid(), 'felipe.herterich@espaciodesafios.cl', 'Felipe Herterich', 'Estimulación Temprana', 'professional', true),
  (gen_random_uuid(), 'felipe.portillo@espaciodesafios.cl', 'Felipe Portillo', 'Psicopedagogía', 'professional', true),
  (gen_random_uuid(), 'fran.maciel@espaciodesafios.cl', 'Fran Maciel Fagundez', 'Psicología', 'professional', true),
  (gen_random_uuid(), 'franco.aguado@espaciodesafios.cl', 'Franco Aguado', 'Fonoaudiología', 'professional', true),
  (gen_random_uuid(), 'gabriel.rodriguez@espaciodesafios.cl', 'Gabriel Rodriguez', 'Terapia Ocupacional', 'professional', true),
  (gen_random_uuid(), 'gadiel.huaylla@espaciodesafios.cl', 'Gadiel Huaylla', 'Kinesiología', 'professional', true),
  (gen_random_uuid(), 'helena.martinez@espaciodesafios.cl', 'Helena Martinez', 'Musicoterapia', 'professional', true),
  (gen_random_uuid(), 'hernan.flores@espaciodesafios.cl', 'Hernan Flores', 'Psicomotricidad Relacional', 'professional', true),
  (gen_random_uuid(), 'ian.orrego@espaciodesafios.cl', 'Ian Orrego', 'Estimulación Temprana', 'professional', true),
  (gen_random_uuid(), 'ignacio.gonzalo@espaciodesafios.cl', 'Ignacio Gonzalo', 'Psicopedagogía', 'professional', true),
  (gen_random_uuid(), 'ignacio.herrera@espaciodesafios.cl', 'Ignacio Herrera', 'Psicología', 'professional', true),
  (gen_random_uuid(), 'ignacio.ojeda@espaciodesafios.cl', 'Ignacio Ojeda', 'Fonoaudiología', 'professional', true),
  (gen_random_uuid(), 'iker.flores@espaciodesafios.cl', 'Iker Flores', 'Terapia Ocupacional', 'professional', true),
  (gen_random_uuid(), 'isaias.baez@espaciodesafios.cl', 'Isaias Baez', 'Kinesiología', 'professional', true),
  (gen_random_uuid(), 'italia.chavez@espaciodesafios.cl', 'Italia Chavez', 'Musicoterapia', 'professional', true),
  (gen_random_uuid(), 'joaquin.garelli@espaciodesafios.cl', 'Joaquin Garelli', 'Psicomotricidad Relacional', 'professional', true),
  (gen_random_uuid(), 'kaila.villalba@espaciodesafios.cl', 'Kaila Villalba', 'Estimulación Temprana', 'professional', true),
  (gen_random_uuid(), 'liam.mendez@espaciodesafios.cl', 'Liam Mendez', 'Psicopedagogía', 'professional', true),
  (gen_random_uuid(), 'lian.mendez@espaciodesafios.cl', 'Lian Mendez', 'Psicología', 'professional', true),
  (gen_random_uuid(), 'lionel.escobar@espaciodesafios.cl', 'Lionel Escobar', 'Fonoaudiología', 'professional', true),
  (gen_random_uuid(), 'luciano.nunez@espaciodesafios.cl', 'Luciano Nuñez', 'Terapia Ocupacional', 'professional', true),
  (gen_random_uuid(), 'luis.lopez@espaciodesafios.cl', 'Luis Lopez', 'Kinesiología', 'professional', true),
  (gen_random_uuid(), 'luan.robledo@espaciodesafios.cl', 'Luan Robledo', 'Musicoterapia', 'professional', true),
  (gen_random_uuid(), 'maite.barraza@espaciodesafios.cl', 'Maite Barraza', 'Psicomotricidad Relacional', 'professional', true),
  (gen_random_uuid(), 'martina.cerchiari@espaciodesafios.cl', 'Martina Cerchiari', 'Estimulación Temprana', 'professional', true),
  (gen_random_uuid(), 'mateo.anse@espaciodesafios.cl', 'Mateo Anse', 'Psicopedagogía', 'professional', true),
  (gen_random_uuid(), 'mateo.molina@espaciodesafios.cl', 'Mateo Molina', 'Psicología', 'professional', true),
  (gen_random_uuid(), 'matias.luna@espaciodesafios.cl', 'Matias Luna', 'Fonoaudiología', 'professional', true),
  (gen_random_uuid(), 'maximo.canseco@espaciodesafios.cl', 'Maximo Canseco', 'Terapia Ocupacional', 'professional', true),
  (gen_random_uuid(), 'nahitan.ona@espaciodesafios.cl', 'Nahitan Oña', 'Kinesiología', 'professional', true),
  (gen_random_uuid(), 'naomi@espaciodesafios.cl', 'Naomi', 'Musicoterapia', 'professional', true),
  (gen_random_uuid(), 'noah.fagundez@espaciodesafios.cl', 'Noah Fagundez', 'Psicomotricidad Relacional', 'professional', true),
  (gen_random_uuid(), 'otto.stale@espaciodesafios.cl', 'Otto Stale', 'Estimulación Temprana', 'professional', true),
  (gen_random_uuid(), 'pedro.lencina@espaciodesafios.cl', 'Pedro Lencina', 'Psicopedagogía', 'professional', true),
  (gen_random_uuid(), 'pia.saavedra@espaciodesafios.cl', 'Pia Saavedra', 'Psicología', 'professional', true),
  (gen_random_uuid(), 'pilar.mamani@espaciodesafios.cl', 'Pilar Mamani', 'Fonoaudiología', 'professional', true),
  (gen_random_uuid(), 'samuel.godoy@espaciodesafios.cl', 'Samuel Godoy', 'Terapia Ocupacional', 'professional', true),
  (gen_random_uuid(), 'santiago.wasinger@espaciodesafios.cl', 'Santiago Wasinger', 'Kinesiología', 'professional', true),
  (gen_random_uuid(), 'santino.lopez@espaciodesafios.cl', 'Santino Lopez', 'Musicoterapia', 'professional', true),
  (gen_random_uuid(), 'stefano.sosa@espaciodesafios.cl', 'Stefano Sosa', 'Psicomotricidad Relacional', 'professional', true),
  (gen_random_uuid(), 'taylor.quiroga@espaciodesafios.cl', 'Taylor Quiroga', 'Estimulación Temprana', 'professional', true),
  (gen_random_uuid(), 'thiago.cider@espaciodesafios.cl', 'Thiago Cider', 'Psicopedagogía', 'professional', true),
  (gen_random_uuid(), 'thiago.rusch@espaciodesafios.cl', 'Thiago Rusch', 'Psicología', 'professional', true),
  (gen_random_uuid(), 'tiziano@espaciodesafios.cl', 'Tiziano', 'Fonoaudiología', 'professional', true),
  (gen_random_uuid(), 'triana.heis@espaciodesafios.cl', 'Triana Heis', 'Terapia Ocupacional', 'professional', true),
  (gen_random_uuid(), 'valentino.meza@espaciodesafios.cl', 'Valentino Meza', 'Kinesiología', 'professional', true),
  (gen_random_uuid(), 'victoria.herrera@espaciodesafios.cl', 'Victoria Herrera', 'Musicoterapia', 'professional', true);

-- Verificar la inserción
SELECT COUNT(*) as total_profesionales FROM profiles WHERE role = 'professional';
