-- Script para insertar profesionales SIN especialidad ni email
-- Solo nombres como solicitó el usuario
-- Ejecutar en Supabase SQL Editor

INSERT INTO profiles (id, full_name, role, is_active) VALUES
  (gen_random_uuid(), 'Abril Villalba', 'professional', true),
  (gen_random_uuid(), 'Agostina Acevedo', 'professional', true),
  (gen_random_uuid(), 'Alejo Herrera', 'professional', true),
  (gen_random_uuid(), 'Alvaro Robledo', 'professional', true),
  (gen_random_uuid(), 'Amber Alleguero', 'professional', true),
  (gen_random_uuid(), 'Antonella Vera Romero', 'professional', true),
  (gen_random_uuid(), 'Beltran Coronel', 'professional', true),
  (gen_random_uuid(), 'Benjamín Wasinger', 'professional', true),
  (gen_random_uuid(), 'Benjamin Benitez', 'professional', true),
  (gen_random_uuid(), 'Benjamin Mamani', 'professional', true),
  (gen_random_uuid(), 'Bruno Orellana', 'professional', true),
  (gen_random_uuid(), 'Camilo Maciel', 'professional', true),
  (gen_random_uuid(), 'Candela Torres', 'professional', true),
  (gen_random_uuid(), 'Carla Fernandez', 'professional', true),
  (gen_random_uuid(), 'Cata Gomez', 'professional', true),
  (gen_random_uuid(), 'Constantino', 'professional', true),
  (gen_random_uuid(), 'Dylan Godoy', 'professional', true),
  (gen_random_uuid(), 'Elias Alvelo', 'professional', true),
  (gen_random_uuid(), 'Ema Cisneros', 'professional', true),
  (gen_random_uuid(), 'Emanuel Cisneros', 'professional', true),
  (gen_random_uuid(), 'Emilio Russo', 'professional', true),
  (gen_random_uuid(), 'Emily Garcia', 'professional', true),
  (gen_random_uuid(), 'Emma Dos Santos', 'professional', true),
  (gen_random_uuid(), 'Espiniza Joaquin', 'professional', true),
  (gen_random_uuid(), 'Felipe Galvan', 'professional', true),
  (gen_random_uuid(), 'Felipe Herterich', 'professional', true),
  (gen_random_uuid(), 'Felipe Portillo', 'professional', true),
  (gen_random_uuid(), 'Fran Maciel Fagundez', 'professional', true),
  (gen_random_uuid(), 'Franco Aguado', 'professional', true),
  (gen_random_uuid(), 'Gabriel Rodriguez', 'professional', true),
  (gen_random_uuid(), 'Gadiel Huaylla', 'professional', true),
  (gen_random_uuid(), 'Helena Martinez', 'professional', true),
  (gen_random_uuid(), 'Hernan Flores', 'professional', true),
  (gen_random_uuid(), 'Ian Orrego', 'professional', true),
  (gen_random_uuid(), 'Ignacio Gonzalo', 'professional', true),
  (gen_random_uuid(), 'Ignacio Herrera', 'professional', true),
  (gen_random_uuid(), 'Ignacio Ojeda', 'professional', true),
  (gen_random_uuid(), 'Iker Flores', 'professional', true),
  (gen_random_uuid(), 'Isaias Baez', 'professional', true),
  (gen_random_uuid(), 'Italia Chavez', 'professional', true),
  (gen_random_uuid(), 'Joaquin Espindola', 'professional', true),
  (gen_random_uuid(), 'Joaquin Garelli', 'professional', true),
  (gen_random_uuid(), 'Kaila Villalba', 'professional', true),
  (gen_random_uuid(), 'Liam Mendez', 'professional', true),
  (gen_random_uuid(), 'Lian Mendez', 'professional', true),
  (gen_random_uuid(), 'Lionel Escobar', 'professional', true),
  (gen_random_uuid(), 'Luciano Nuñez', 'professional', true),
  (gen_random_uuid(), 'Luis Lopez', 'professional', true),
  (gen_random_uuid(), 'Luan Robledo', 'professional', true),
  (gen_random_uuid(), 'Maite Barraza', 'professional', true),
  (gen_random_uuid(), 'Martina Cerchiari', 'professional', true),
  (gen_random_uuid(), 'Mateo Anse', 'professional', true),
  (gen_random_uuid(), 'Mateo Molina', 'professional', true),
  (gen_random_uuid(), 'Matias Luna', 'professional', true),
  (gen_random_uuid(), 'Maximo Canseco', 'professional', true),
  (gen_random_uuid(), 'Nahitan Oña', 'professional', true),
  (gen_random_uuid(), 'Naomi', 'professional', true),
  (gen_random_uuid(), 'Noah Fagundez', 'professional', true),
  (gen_random_uuid(), 'Otto Stale', 'professional', true),
  (gen_random_uuid(), 'Pedro Lencina', 'professional', true),
  (gen_random_uuid(), 'Pia Saavedra', 'professional', true),
  (gen_random_uuid(), 'Pilar Mamani', 'professional', true),
  (gen_random_uuid(), 'Samuel Godoy', 'professional', true),
  (gen_random_uuid(), 'Santiago Wasinger', 'professional', true),
  (gen_random_uuid(), 'Santino Lopez', 'professional', true),
  (gen_random_uuid(), 'Stefano Sosa', 'professional', true),
  (gen_random_uuid(), 'Taylor Quiroga', 'professional', true),
  (gen_random_uuid(), 'Thiago Cider', 'professional', true),
  (gen_random_uuid(), 'Thiago Rusch', 'professional', true),
  (gen_random_uuid(), 'Tiziano', 'professional', true),
  (gen_random_uuid(), 'Triana Heis', 'professional', true),
  (gen_random_uuid(), 'Valentino Meza', 'professional', true),
  (gen_random_uuid(), 'Victoria Herrera', 'professional', true);

-- Verificar la inserción
SELECT COUNT(*) as total_profesionales FROM profiles WHERE role = 'professional' AND email IS NULL;
